version: 2

orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      # ビルド
      - run: npm build
      # cliからNetlifyにデプロイできるようにするライブラリをインストール
      - run: npm install netlify-cli
      # デプロイコマンド
      - run: npm netlify deploy -p -d wonderful-cray-9a9c1f -a auto_cm -s Bx2qmgrqfmNG

workflows:
  version: 2

  test-build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master